### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by pjotrp** [prasunanand/resume#1]
Hi Prasun, already an impressive proposal. I can see your experience of the last year has taught you a lot. I think that the workplan needs more substance. What I mean is that it is not clear to us what Arrayfire and OpenCL exactly offer and if you can expand on that with URLs and actual intent of writing bindings, unit tests and what it will look like for the end user that would be great!

**Comment by prasunanand** [comment]
Thank You :)

I have added the changes.

Comparing Opencl and Arrayfire
https://github.com/prasunanand/resume/wiki/GSoC-2017-proposal#comparing-opencl-and-arrayfire

**Comment by prasunanand** [comment]
Test suite:
https://github.com/prasunanand/resume/wiki/GSoC-2017-proposal#tdd

Targeted Functionality for End-user:
https://github.com/prasunanand/resume/wiki/GSoC-2017-proposal#targeted-functionality-for-end-user

**Comment by pjotrp** [comment]
You could add that Arrayfire allows matrix operations exceeding GPU RAM. That is correct, right? In that way it acts more like Cudablas. You should check Clblas  if it does that too.

Arrayfire can use OpenCL, right? If so, add that.

NVIDIA is also supporting OpenCL. Can you check the status? Please add.

TDD and functionality look good. Now add them explicitely to the workplan. 

I miss sorting...

**Comment by prasunanand** [comment]
**You could add that Arrayfire allows matrix operations exceeding GPU RAM. That is correct, right?**
Yes

**In that way it acts more like Cudablas. You should check Clblas if it does that too.**

Yes. [Link](https://github.com/clMathLibraries/clBLAS/wiki/Design#common-organization)
It allows getting the best decomposition block sizes for the problem from the kernel database file.

**Arrayfire can use OpenCL, right? If so, add that.**

Yeah. I missed to add it.

**NVIDIA is also supporting OpenCL. Can you check the status? Please add.**

Yes. Adding it. [Link](https://developer.nvidia.com/opencl)
I found out from a [blog](https://cnugteren.github.io/tutorial/pages/page15.html) that NVIDIA provides more GFLOPS than AMD GPUs.

Added benefit is that when a user runs ArrayFire, it firse checks for CUDA, then it falls to OpenCL, next to CPU.

**TDD and functionality look good. Now add them explicitely to the workplan.**
Will do.

**I miss sorting...**
On it.

**Comment by prasunanand** [comment]
@pjotrp I have made the changes.

Sorting apis are already provided by ArrayFire which I have added to the plan.

**Comment by pjotrp** [comment]
Hi Prasun, certainly looking better. To improve the proposal:

1. Add more URLs when pointing to other information (technical documents and such)
2. The plan has improved, but I think we can have better granularity. Can you make it a weekly plan?
3. Can you say something about the challenge of your proposal? Compare it with the work you have done last year - how challenging is this going to be?
4. It may be an idea to update something on SciRuby and make a PR. Can you think of anything related to this work which may already be worth merging? You have been working on arrayfire earlier.

**Comment by prasunanand** [comment]
Hi,
 **1. Add more URLs when pointing to other information (technical documents and such)**
On it.
**2. The plan has improved, but I think we can have better granularity. Can you make it a weekly plan?**
Yes
**Can you say something about the challenge of your proposal? Compare it with the work you have done last year - how challenging is this going to be?**
On it.
**It may be an idea to update something on SciRuby and make a PR. Can you think of anything related to this work which may already be worth merging? You have been working on arrayfire earlier.**

* I am yet to make a PR to arrayfire/arrayfire-rb regarding implementing 2D matrices for MRI.

* I think of starting a discussion on ML regarding interfacing NMatrix with ArrayFire. After coming to a conclusion on what would be the best practice, I can get some of the features merged to NMatrix.
Daru wraps to NMatrix and gsl using [wrappers](https://github.com/SciRuby/daru/tree/7e7008e938f236ba55905560015683e1fde7d971/lib/daru/accessors).

**Comment by prasunanand** [comment]
@pjotrp: I have added the changes.
